version: '3'

services:
  db:
    image: postgres:16
    container_name: my_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aavel
      POSTGRES_PASSWORD: "tu_contraseña_correcta"
      POSTGRES_DB: mydatabase
    volumes:
      - ./postgres:/var/lib/postgresql/data